-- MySQL Script generated by MySQL Workbench
-- Wed Feb 10 23:34:41 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema DB-FACEBOOK
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema DB-FACEBOOK
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DB-FACEBOOK` DEFAULT CHARACTER SET utf8 ;
USE `DB-FACEBOOK` ;

-- -----------------------------------------------------
-- Table `DB-FACEBOOK`.`gender`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB-FACEBOOK`.`gender` (
  `genderId` INT NOT NULL AUTO_INCREMENT,
  `gender` VARCHAR(45) NOT NULL,
  `abrev` VARCHAR(1) NOT NULL,
  PRIMARY KEY (`genderId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB-FACEBOOK`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB-FACEBOOK`.`user` (
  `userId` INT NOT NULL AUTO_INCREMENT,
  `genderId` INT NOT NULL,
  `firstName` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  `profileAvatar` VARCHAR(255) NULL,
  PRIMARY KEY (`userId`),
  INDEX `fk_user_gender1_idx` (`genderId` ASC) VISIBLE,
  CONSTRAINT `fk_user_gender1`
    FOREIGN KEY (`genderId`)
    REFERENCES `DB-FACEBOOK`.`gender` (`genderId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB-FACEBOOK`.`post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB-FACEBOOK`.`post` (
  `postId` INT NOT NULL AUTO_INCREMENT,
  `userId` INT NOT NULL,
  `post` VARCHAR(255) NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`postId`),
  INDEX `fk_post_user_idx` (`userId` ASC) VISIBLE,
  CONSTRAINT `fk_post_user`
    FOREIGN KEY (`userId`)
    REFERENCES `DB-FACEBOOK`.`user` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
