-- MySQL Script generated by MySQL Workbench
-- Wed Oct 14 15:34:12 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db-articles-store
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db-articles-store
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db-articles-store` DEFAULT CHARACTER SET utf8 ;
USE `db-articles-store` ;

-- -----------------------------------------------------
-- Table `db-articles-store`.`tbl_article_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db-articles-store`.`tbl_article_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `article_type` VARCHAR(45) NOT NULL,
  `article_abrev` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db-articles-store`.`tbl_articles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db-articles-store`.`tbl_articles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `article_type_id` INT NOT NULL,
  `article_name` VARCHAR(45) NOT NULL,
  `article_description` VARCHAR(150) NOT NULL,
  `article_price` DECIMAL NOT NULL,
  `article_stock` INT NOT NULL
  PRIMARY KEY (`id`),
  INDEX `fk_tbl_articles_tbl_article_type_idx` (`article_type_id` ASC),
  CONSTRAINT `fk_tbl_articles_tbl_article_type`
    FOREIGN KEY (`article_type_id`)
    REFERENCES `db-articles-store`.`tbl_article_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
ALTER TABLE tbl_articles ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
INSERT INTO `tbl_articles` (`id`, `article_type_id`, `article_name`, `article_description`, `article_price`, `article_stock`) VALUES (NULL, '1', 'Coca Cola', 'Bebida refrescante para todas las edades', '15.00', '50');
INSERT INTO tbl_article_type (article_type , article_abrev) VALUES ("Bebidas","Beb");


